name: Build Native Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-native-image:
    name: Build Native on Linux x64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Set up GraalVM (Mandrel is optimized for Quarkus)
      - name: Set up GraalVM (Mandrel)
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'          # Match this to your project's Java version
          distribution: 'mandrel'     # Recommended for Quarkus
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Cache Gradle packages to speed up future builds
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 3. Make Gradlew Executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Build the Native Executable
      # -x test skips the tests to save time
      # We use -Dquarkus.package.type=native to avoid the "Outputting both native and JAR" error
      - name: Build Native Executable
        run: ./gradlew build -Dquarkus.package.type=native -x test


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -f src/main/docker/Dockerfile.native -t ghcr.io/${{ env.IMAGE_NAME }}:latest .

      # 6. Push the image
      - name: Push Docker Image
        run: docker push ghcr.io/${{ env.IMAGE_NAME }}:latest